Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos0.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos1.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos2.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos3.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos4.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos5.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos6.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos7.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos8.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
Invoke-WebRequest https://dadosabertos.rfb.gov.br/CNPJ/Estabelecimentos9.zip -OutFile ./DataCNPJ/zip/Estabelecimentos0.zip
